project:
  name: canonical_real_to_mannequin_pose_inpaint_2000_768x1024_50ep_run44_keepblend
  output_dir: ./outputs/run44_canonical_real_to_mannequin_pose_inpaint_2000_768x1024_50ep_keepblend
  seed: 42
  canonical_pose_inpaint: true
  fixed_prompt: "a smooth glossy white plastic retail mannequin, clearly non-human mannequin body, rigid mannequin limbs, no human skin, no flesh, no realistic face, keep the exact clothes, garment texture, garment silhouette, pose, composition, and white background"

data:
  all_metadata_path: ./datasets/canonical_real_to_mannequin_pose_inpaint_2000_768x1024/metadata_all.jsonl
  train_metadata_path: ./datasets/canonical_real_to_mannequin_pose_inpaint_2000_768x1024/metadata_train_latent_cached_768x1024.jsonl
  val_metadata_path: ./datasets/canonical_real_to_mannequin_pose_inpaint_2000_768x1024/metadata_val.jsonl
  image_size: 768
  image_width: 768
  image_height: 1024
  center_crop: false
  random_flip: false
  prompt_dropout: 0.0
  invert_mask: true
  source_background_value: 255
  conditioning_resize_modes:
    - nearest

model:
  base_mode: inpaint
  pretrained_model_name_or_path: /home/ouyanghaodong/.cache/huggingface/hub/models--diffusers--stable-diffusion-xl-1.0-inpainting-0.1/snapshots/115134f363124c53c7d878647567d04daf26e41e
  controlnet_model_name_or_path: ./models/controlnet-openpose-sdxl-1.0-xinsir
  controlnet_model_name_or_paths: null
  num_controlnets: 1
  vae_model_name_or_path: null
  revision: null
  variant: fp16
  prediction_type: epsilon
  attention_slicing: false
  controlnet_train_dtype: bf16
  dynamic_vae_encode_on_gpu: true
  unet_base_dtype: bf16

inference:
  metadata_path: ./datasets/canonical_real_to_mannequin_pose_inpaint_2000_768x1024/subsets/metadata_val_subset10_same.jsonl
  checkpoint_dir: ./outputs/run44_canonical_real_to_mannequin_pose_inpaint_2000_768x1024_50ep_keepblend/checkpoints/final
  output_dir: ./outputs/run44_scale07_subset10_promptv2/infer_subset10
  prompt: "a smooth glossy white plastic retail mannequin, clearly non-human mannequin body, rigid mannequin limbs, no human skin, no flesh, no realistic face, keep the exact clothes, garment texture, garment silhouette, pose, composition, and white background"
  negative_prompt: "human, real person, hair, hat, complex background"
  num_inference_steps: 30
  guidance_scale: 5.0
  controlnet_conditioning_scale:
    - 0.7
  strength: 1.0
  invert_mask: true
  enforce_keep_region_blend: true
  enable_model_cpu_offload: true
  generate_pairs: true
  pair_output_dir: ./outputs/run44_scale07_subset10_promptv2/original_generated_pairs
  generate_debug_composites: true
  debug_output_dir: ./outputs/run44_scale07_subset10_promptv2/inference_debug_composites
  run_after_train: false
