project:
  name: sdxl_controlnet_inpaint_project
  output_dir: ./outputs/run8_full400_invert_mask_50ep
  seed: 42

data:
  all_metadata_path: ./examples/metadata_all_real_to_mannequin.jsonl
  train_metadata_path: ./examples/metadata_train_real_to_mannequin.jsonl
  val_metadata_path: ./examples/metadata_val_real_to_mannequin.jsonl
  image_size: 384
  image_width: 384
  image_height: 512
  center_crop: false
  random_flip: false
  mask_dilate: 0
  prompt_dropout: 0.0
  invert_mask: true

model:
  pretrained_model_name_or_path: diffusers/stable-diffusion-xl-1.0-inpainting-0.1
  controlnet_model_name_or_path: null
  vae_model_name_or_path: null
  revision: null
  variant: fp16
  conditioning_type: segmentation
  prediction_type: epsilon

training:
  train_batch_size: 1
  num_workers: 0
  num_epochs: 50
  max_train_steps: 19000
  gradient_accumulation_steps: 1
  learning_rate: 5.0e-6
  weight_decay: 1.0e-2
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8
  max_grad_norm: 1.0
  lr_scheduler: constant
  lr_warmup_steps: 0
  mixed_precision: "fp16"
  gradient_checkpointing: true
  resume_from_checkpoint: null
  save_every_steps: 1000
  validate_every_steps: 0

validation:
  num_inference_steps: 30
  guidance_scale: 5.0
  max_val_samples: 4

inference:
  metadata_path: ./examples/metadata_val_real_to_mannequin.jsonl
  checkpoint_dir: ./outputs/run8_full400_invert_mask_50ep/checkpoints/final/controlnet
  output_dir: ./outputs/run8_full400_invert_mask_50ep/infer_test20
  prompt: null
  source_image: null
  mask_image: null
  conditioning_image: null
  output_path: ./outputs/infer/sample.png
  negative_prompt: "low quality, blurry, distorted, deformed body, broken clothes, extra limbs"
  num_inference_steps: 30
  guidance_scale: 5.0
  controlnet_conditioning_scale: 1.0
  strength: 0.85
  invert_mask: true
